builds: add missing linux-headers to env
The build was failing with this error:

programs/sxmo_vibrate.c:16:10: fatal error: linux/input.h: No such file or directory
   16 | #include <linux/input.h>

Signed-off-by: Aren Moynihan <aren@peacevolution.org>